languageCode = "JP"
title = "アサテイ！"
baseurl = "/"
paginate = 30
buildFuture = false
preserveTaxonomyNames = true

[Params]
description = "牛丼チェーン店をはじめとする、朝定食のまとめサイトです。"

[params.strings]
date_format = "2006-1-2"
