languageCode = "JP"
title = "アサテイ！"
baseurl = "https://asatei.h000.net/"
paginate = 30
buildFuture = false
preserveTaxonomyNames = true

[Params]
description = "朝定食くらべました。牛丼チェーン店をはじめとする、朝定食メニューの比較・まとめサイトです。"

[params.strings]
date_format = "2006-1-2"
