languageCode = "ja-jp"
title = "アサテイ！"
baseurl = "/"
paginate = 12
buildFuture = false

[taxonomies]
tag = "tags"

[Params]
description = "牛丼チェーン店をはじめとする、朝定食のまとめサイトです。"

[params.strings]
date_format = "2006-1-2"
